package git_workflow.calc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;

   public Item()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public Item(java.lang.String type)
   {
      this.type = type;
   }

}